<?xml version="1.0" encoding="utf-8"?>
<TestRun id="ae8a4385-a4b7-4015-a3ff-4baaef77f941" name="@Cray 2025-08-22 19:30:17" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2025-08-22T19:30:17.5746661+01:00" queuing="2025-08-22T19:30:17.5746662+01:00" start="2025-08-22T19:30:16.7550096+01:00" finish="2025-08-22T19:30:20.7889993+01:00" />
  <TestSettings name="default" id="789df399-6d3f-4ba0-96fd-5379bc2be273">
    <Deployment runDeploymentRoot="_Cray_2025-08-22_19_30_17" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="04d01529-f553-4d8f-92be-8adc97e3a64b" testId="d3fcf216-dd2c-df24-3944-6635f054888d" testName="RoslynMcpServer.Tests.ToolTests.TestSymbolFormatting_Produces_Some_Symbols" computerName="Cray" duration="00:00:00.0010000" startTime="2025-08-22T19:30:20.7422214+01:00" endTime="2025-08-22T19:30:20.7422216+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="04d01529-f553-4d8f-92be-8adc97e3a64b">
      <Output>
        <ErrorInfo>
          <Message>Expected res.IsError to be false, but found &lt;null&gt;.</Message>
          <StackTrace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
   at RoslynMcpServer.Tests.ToolTests.InitializeAsync() in /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs:line 46</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="41244bc4-dde6-4069-b2a0-e247db1c9233" testId="7d403ef7-81dc-159c-5ac0-909dedbd349a" testName="RoslynMcpServer.Tests.ToolTests.GetTypeInfo_ReturnsMembers_ForMathUtils" computerName="Cray" duration="00:00:00.0010000" startTime="2025-08-22T19:30:17.0516826+01:00" endTime="2025-08-22T19:30:17.0516827+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="41244bc4-dde6-4069-b2a0-e247db1c9233">
      <Output>
        <ErrorInfo>
          <Message>Expected res.IsError to be false, but found &lt;null&gt;.</Message>
          <StackTrace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
   at RoslynMcpServer.Tests.ToolTests.InitializeAsync() in /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs:line 46</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="22ff4d69-6521-4708-9263-4870b160d940" testId="f28277a6-d058-af65-5e1c-4f9be2217b58" testName="RoslynMcpServer.Tests.ToolTests.DescribeSymbol_ByFqn_Returns_Type_Info" computerName="Cray" duration="00:00:00.0010000" startTime="2025-08-22T19:30:16.1337104+01:00" endTime="2025-08-22T19:30:16.1337195+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="22ff4d69-6521-4708-9263-4870b160d940">
      <Output>
        <ErrorInfo>
          <Message>Expected res.IsError to be false, but found &lt;null&gt;.</Message>
          <StackTrace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
   at RoslynMcpServer.Tests.ToolTests.InitializeAsync() in /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs:line 46</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="7b95f83b-2cac-4629-a937-537d9b6b97b3" testId="647d9059-f27e-1a1c-d900-820c35eb2238" testName="RoslynMcpServer.Tests.ToolTests.FindReferences_Finds_Usages_Of_Add_Method" computerName="Cray" duration="00:00:00.0010000" startTime="2025-08-22T19:30:19.8179814+01:00" endTime="2025-08-22T19:30:19.8179816+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7b95f83b-2cac-4629-a937-537d9b6b97b3">
      <Output>
        <ErrorInfo>
          <Message>Expected res.IsError to be false, but found &lt;null&gt;.</Message>
          <StackTrace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
   at RoslynMcpServer.Tests.ToolTests.InitializeAsync() in /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs:line 46</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="22c99410-63db-4b64-8096-4607115fdfa7" testId="66d58358-3b77-5068-9600-68885ac7034b" testName="RoslynMcpServer.Tests.ToolTests.GetMethodDependencies_Reports_Calls_Reads_Writes" computerName="Cray" duration="00:00:00.0010000" startTime="2025-08-22T19:30:18.9171281+01:00" endTime="2025-08-22T19:30:18.9171283+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="22c99410-63db-4b64-8096-4607115fdfa7">
      <Output>
        <ErrorInfo>
          <Message>Expected res.IsError to be false, but found &lt;null&gt;.</Message>
          <StackTrace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
   at RoslynMcpServer.Tests.ToolTests.InitializeAsync() in /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs:line 46</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="790b7e0b-02b9-43a4-9cd7-ed783c55f40a" testId="b24600ce-ce49-a9b2-61f2-c0f08591ddd9" testName="RoslynMcpServer.Tests.ToolTests.GotoDefinition_Returns_Source_Location_For_Method" computerName="Cray" duration="00:00:00.0010000" startTime="2025-08-22T19:30:17.9618795+01:00" endTime="2025-08-22T19:30:17.9618797+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="790b7e0b-02b9-43a4-9cd7-ed783c55f40a">
      <Output>
        <ErrorInfo>
          <Message>Expected res.IsError to be false, but found &lt;null&gt;.</Message>
          <StackTrace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
   at RoslynMcpServer.Tests.ToolTests.InitializeAsync() in /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs:line 46</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="RoslynMcpServer.Tests.ToolTests.GetMethodDependencies_Reports_Calls_Reads_Writes" storage="/mnt/c/users/newon/source/repos/roslynmcpserver/tests/roslynmcpserver.tests/bin/debug/net9.0/roslynmcpserver.tests.dll" id="66d58358-3b77-5068-9600-68885ac7034b">
      <Execution id="22c99410-63db-4b64-8096-4607115fdfa7" />
      <TestMethod codeBase="/mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/bin/Debug/net9.0/RoslynMcpServer.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="RoslynMcpServer.Tests.ToolTests" name="GetMethodDependencies_Reports_Calls_Reads_Writes" />
    </UnitTest>
    <UnitTest name="RoslynMcpServer.Tests.ToolTests.TestSymbolFormatting_Produces_Some_Symbols" storage="/mnt/c/users/newon/source/repos/roslynmcpserver/tests/roslynmcpserver.tests/bin/debug/net9.0/roslynmcpserver.tests.dll" id="d3fcf216-dd2c-df24-3944-6635f054888d">
      <Execution id="04d01529-f553-4d8f-92be-8adc97e3a64b" />
      <TestMethod codeBase="/mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/bin/Debug/net9.0/RoslynMcpServer.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="RoslynMcpServer.Tests.ToolTests" name="TestSymbolFormatting_Produces_Some_Symbols" />
    </UnitTest>
    <UnitTest name="RoslynMcpServer.Tests.ToolTests.FindReferences_Finds_Usages_Of_Add_Method" storage="/mnt/c/users/newon/source/repos/roslynmcpserver/tests/roslynmcpserver.tests/bin/debug/net9.0/roslynmcpserver.tests.dll" id="647d9059-f27e-1a1c-d900-820c35eb2238">
      <Execution id="7b95f83b-2cac-4629-a937-537d9b6b97b3" />
      <TestMethod codeBase="/mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/bin/Debug/net9.0/RoslynMcpServer.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="RoslynMcpServer.Tests.ToolTests" name="FindReferences_Finds_Usages_Of_Add_Method" />
    </UnitTest>
    <UnitTest name="RoslynMcpServer.Tests.ToolTests.DescribeSymbol_ByFqn_Returns_Type_Info" storage="/mnt/c/users/newon/source/repos/roslynmcpserver/tests/roslynmcpserver.tests/bin/debug/net9.0/roslynmcpserver.tests.dll" id="f28277a6-d058-af65-5e1c-4f9be2217b58">
      <Execution id="22ff4d69-6521-4708-9263-4870b160d940" />
      <TestMethod codeBase="/mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/bin/Debug/net9.0/RoslynMcpServer.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="RoslynMcpServer.Tests.ToolTests" name="DescribeSymbol_ByFqn_Returns_Type_Info" />
    </UnitTest>
    <UnitTest name="RoslynMcpServer.Tests.ToolTests.GetTypeInfo_ReturnsMembers_ForMathUtils" storage="/mnt/c/users/newon/source/repos/roslynmcpserver/tests/roslynmcpserver.tests/bin/debug/net9.0/roslynmcpserver.tests.dll" id="7d403ef7-81dc-159c-5ac0-909dedbd349a">
      <Execution id="41244bc4-dde6-4069-b2a0-e247db1c9233" />
      <TestMethod codeBase="/mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/bin/Debug/net9.0/RoslynMcpServer.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="RoslynMcpServer.Tests.ToolTests" name="GetTypeInfo_ReturnsMembers_ForMathUtils" />
    </UnitTest>
    <UnitTest name="RoslynMcpServer.Tests.ToolTests.GotoDefinition_Returns_Source_Location_For_Method" storage="/mnt/c/users/newon/source/repos/roslynmcpserver/tests/roslynmcpserver.tests/bin/debug/net9.0/roslynmcpserver.tests.dll" id="b24600ce-ce49-a9b2-61f2-c0f08591ddd9">
      <Execution id="790b7e0b-02b9-43a4-9cd7-ed783c55f40a" />
      <TestMethod codeBase="/mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/bin/Debug/net9.0/RoslynMcpServer.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="RoslynMcpServer.Tests.ToolTests" name="GotoDefinition_Returns_Source_Location_For_Method" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="d3fcf216-dd2c-df24-3944-6635f054888d" executionId="04d01529-f553-4d8f-92be-8adc97e3a64b" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="7d403ef7-81dc-159c-5ac0-909dedbd349a" executionId="41244bc4-dde6-4069-b2a0-e247db1c9233" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="f28277a6-d058-af65-5e1c-4f9be2217b58" executionId="22ff4d69-6521-4708-9263-4870b160d940" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="647d9059-f27e-1a1c-d900-820c35eb2238" executionId="7b95f83b-2cac-4629-a937-537d9b6b97b3" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="66d58358-3b77-5068-9600-68885ac7034b" executionId="22c99410-63db-4b64-8096-4607115fdfa7" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="b24600ce-ce49-a9b2-61f2-c0f08591ddd9" executionId="790b7e0b-02b9-43a4-9cd7-ed783c55f40a" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="6" executed="6" passed="0" failed="6" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2+699d445a1a (64-bit .NET 9.0.8)
[xUnit.net 00:00:00.06]   Discovering: RoslynMcpServer.Tests
[xUnit.net 00:00:00.08]   Discovered:  RoslynMcpServer.Tests
[xUnit.net 00:00:00.08]   Starting:    RoslynMcpServer.Tests
LoadSolutionTool.ExecuteAsync called with arguments: {"path":"/mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj"}
Loading: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Opening: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Loading as project file...
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (net9.0)
Solution loaded: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Projects count: 1
  Project: SampleApp (TFM: net9.0)
Solution load mode: project
[xUnit.net 00:00:01.54]       Expected res.IsError to be false, but found &lt;null&gt;.
[xUnit.net 00:00:01.54]       Stack Trace:
[xUnit.net 00:00:01.54]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:01.54]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[xUnit.net 00:00:01.54]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[xUnit.net 00:00:01.54]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:01.54]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:01.54]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[xUnit.net 00:00:01.54]            at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
[xUnit.net 00:00:01.54]         /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs(46,0): at RoslynMcpServer.Tests.ToolTests.InitializeAsync()
LoadSolutionTool.ExecuteAsync called with arguments: {"path":"/mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj"}
Loading: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Opening: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Loading as project file...
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (net9.0)
Solution loaded: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Projects count: 1
  Project: SampleApp (TFM: net9.0)
Solution load mode: project
[xUnit.net 00:00:02.46]       Expected res.IsError to be false, but found &lt;null&gt;.
[xUnit.net 00:00:02.46]       Stack Trace:
[xUnit.net 00:00:02.46]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:02.46]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[xUnit.net 00:00:02.46]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[xUnit.net 00:00:02.46]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:02.46]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:02.46]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[xUnit.net 00:00:02.46]            at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
[xUnit.net 00:00:02.46]         /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs(46,0): at RoslynMcpServer.Tests.ToolTests.InitializeAsync()
LoadSolutionTool.ExecuteAsync called with arguments: {"path":"/mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj"}
Loading: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Opening: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Loading as project file...
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (net9.0)
Solution loaded: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Projects count: 1
  Project: SampleApp (TFM: net9.0)
Solution load mode: project
[xUnit.net 00:00:03.36]       Expected res.IsError to be false, but found &lt;null&gt;.
[xUnit.net 00:00:03.37]       Stack Trace:
[xUnit.net 00:00:03.37]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:03.37]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[xUnit.net 00:00:03.37]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[xUnit.net 00:00:03.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:03.37]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:03.37]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[xUnit.net 00:00:03.37]            at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
[xUnit.net 00:00:03.37]         /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs(46,0): at RoslynMcpServer.Tests.ToolTests.InitializeAsync()
LoadSolutionTool.ExecuteAsync called with arguments: {"path":"/mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj"}
Loading: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Opening: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Loading as project file...
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (net9.0)
Solution loaded: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Projects count: 1
  Project: SampleApp (TFM: net9.0)
Solution load mode: project
[xUnit.net 00:00:04.33]       Expected res.IsError to be false, but found &lt;null&gt;.
[xUnit.net 00:00:04.33]       Stack Trace:
[xUnit.net 00:00:04.33]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:04.33]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[xUnit.net 00:00:04.33]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[xUnit.net 00:00:04.33]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:04.33]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:04.33]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[xUnit.net 00:00:04.33]            at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
[xUnit.net 00:00:04.33]         /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs(46,0): at RoslynMcpServer.Tests.ToolTests.InitializeAsync()
LoadSolutionTool.ExecuteAsync called with arguments: {"path":"/mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj"}
Loading: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Opening: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Loading as project file...
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (net9.0)
Solution loaded: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Projects count: 1
  Project: SampleApp (TFM: net9.0)
Solution load mode: project
[xUnit.net 00:00:05.23]       Expected res.IsError to be false, but found &lt;null&gt;.
[xUnit.net 00:00:05.23]       Stack Trace:
[xUnit.net 00:00:05.23]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:05.23]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[xUnit.net 00:00:05.23]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[xUnit.net 00:00:05.23]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:05.23]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:05.23]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[xUnit.net 00:00:05.23]            at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
[xUnit.net 00:00:05.23]         /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs(46,0): at RoslynMcpServer.Tests.ToolTests.InitializeAsync()
LoadSolutionTool.ExecuteAsync called with arguments: {"path":"/mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj"}
Loading: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Opening: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Loading as project file...
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (unknown)
Loading /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj (net9.0)
Solution loaded: /mnt/c/Users/newon/source/repos/RoslynMcpServer/samples/SampleApp/SampleApp.csproj
Projects count: 1
  Project: SampleApp (TFM: net9.0)
Solution load mode: project
[xUnit.net 00:00:06.15]       Expected res.IsError to be false, but found &lt;null&gt;.
[xUnit.net 00:00:06.15]       Stack Trace:
[xUnit.net 00:00:06.15]            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[xUnit.net 00:00:06.15]            at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[xUnit.net 00:00:06.15]            at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[xUnit.net 00:00:06.15]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:06.15]            at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
[xUnit.net 00:00:06.15]            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[xUnit.net 00:00:06.15]            at FluentAssertions.Primitives.BooleanAssertions`1.BeFalse(String because, Object[] becauseArgs)
[xUnit.net 00:00:06.15]         /mnt/c/Users/newon/source/repos/RoslynMcpServer/tests/RoslynMcpServer.Tests/ToolTests.cs(46,0): at RoslynMcpServer.Tests.ToolTests.InitializeAsync()
[xUnit.net 00:00:06.16]   Finished:    RoslynMcpServer.Tests
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="Cray" outcome="Error" timestamp="2025-08-22T19:30:16.1329931+01:00">
        <Text>[xUnit.net 00:00:01.54]     RoslynMcpServer.Tests.ToolTests.DescribeSymbol_ByFqn_Returns_Type_Info [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="Cray" outcome="Error" timestamp="2025-08-22T19:30:17.0521057+01:00">
        <Text>[xUnit.net 00:00:02.46]     RoslynMcpServer.Tests.ToolTests.GetTypeInfo_ReturnsMembers_ForMathUtils [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="Cray" outcome="Error" timestamp="2025-08-22T19:30:17.9560460+01:00">
        <Text>[xUnit.net 00:00:03.36]     RoslynMcpServer.Tests.ToolTests.GotoDefinition_Returns_Source_Location_For_Method [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="Cray" outcome="Error" timestamp="2025-08-22T19:30:18.9175057+01:00">
        <Text>[xUnit.net 00:00:04.33]     RoslynMcpServer.Tests.ToolTests.GetMethodDependencies_Reports_Calls_Reads_Writes [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="Cray" outcome="Error" timestamp="2025-08-22T19:30:19.8183172+01:00">
        <Text>[xUnit.net 00:00:05.23]     RoslynMcpServer.Tests.ToolTests.FindReferences_Finds_Usages_Of_Add_Method [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="Cray" outcome="Error" timestamp="2025-08-22T19:30:20.7424111+01:00">
        <Text>[xUnit.net 00:00:06.15]     RoslynMcpServer.Tests.ToolTests.TestSymbolFormatting_Produces_Some_Symbols [FAIL]</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>